# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "balancer" do |balancer|
      balancer.vm.box = "ubuntu/trusty64"
      balancer.vm.network "private_network", ip: "192.168.33.10"
      balancer.vm.provision "shell", path: "install-nginx.sh"
  end

  config.vm.define "node2" do |node2|
      node2.vm.box = "ubuntu/trusty64"
      node2.vm.network "private_network", ip: "192.168.33.2"
      node2.vm.provision "shell", path: "install-nodejs.sh"
  end

  config.vm.define "node3" do |node3|
      node3.vm.box = "ubuntu/trusty64"
      node3.vm.network "private_network", ip: "192.168.33.3"
      node3.vm.provision "shell", path: "install-nodejs.sh"
  end

  config.vm.define "node4" do |node4|
      node4.vm.box = "ubuntu/trusty64"
      node4.vm.network "private_network", ip: "192.168.33.4"
      node4.vm.provision "shell", path: "install-nodejs.sh"
  end

end
